language: python
python:
  - "2.7"
  - "3.3"
install: "pip install -e .; pip install -r test-requires.txt; pip install python-coveralls"
script: "nosetests --nologcapture --with-coverage"
after_success:
  - coveralls
